# Generated by Django 5.2.1 on 2025-05-09 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='models/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('class_names', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='model_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.modelfile'),
        ),
    ]
